<?xml version="1.0" encoding="utf-8"?><Database Name="ProyectoPAvanzada" Class="DatosDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=laptop-8f4n8264\sqlexpress;Initial Catalog=ProyectoPAvanzada;Integrated Security=True" SettingsObjectName="DAL.Properties.Settings" SettingsPropertyName="ProyectoPAvanzadaConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.ActualizaLinea" Method="ActualizaLinea">
    <Parameter Name="IdEmpresa" Parameter="idEmpresa" Type="System.Int32" DbType="Int" />
    <Parameter Name="IdLinea" Parameter="idLinea" Type="System.Int32" DbType="Int" />
    <Parameter Name="Descripcion" Parameter="descripcion" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="CodigoCTP" Parameter="codigoCTP" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Provincia" Parameter="provincia" Type="System.Char" DbType="Char(1)" />
    <Parameter Name="Canton" Parameter="canton" Type="System.String" DbType="Char(2)" />
    <Parameter Name="Distrito" Parameter="distrito" Type="System.String" DbType="Char(2)" />
    <Parameter Name="Estado" Parameter="estado" Type="System.Boolean" DbType="Bit" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.ActualizaUsuario" Method="ActualizaUsuario">
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Int32" DbType="Int" />
    <Parameter Name="Nombre" Parameter="nombre" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Nombre2" Parameter="nombre2" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Apellido1" Parameter="apellido1" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Apellido2" Parameter="apellido2" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="IdTipoIdentificacion" Parameter="idTipoIdentificacion" Type="System.Int32" DbType="Int" />
    <Parameter Name="Identificacion" Parameter="identificacion" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Saldo" Parameter="saldo" Type="System.Decimal" DbType="Money" />
    <Parameter Name="Telefono" Parameter="telefono" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Correo" Parameter="correo" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Clave" Parameter="clave" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Estado" Parameter="estado" Type="System.Boolean" DbType="Bit" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Cantones" Method="Cantones">
    <Parameter Name="Provincia" Parameter="provincia" Type="System.Char" DbType="Char(1)" />
    <ElementType Name="CantonesResult">
      <Column Name="Provincia" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="Canton" Type="System.String" DbType="Char(2) NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.ConsultaLinea" Method="ConsultaLinea">
    <Parameter Name="IdEmpresa" Parameter="idEmpresa" Type="System.Int32" DbType="Int" />
    <Parameter Name="IdLinea" Parameter="idLinea" Type="System.Int32" DbType="Int" />
    <ElementType Name="ConsultaLineaResult">
      <Column Name="IdLinea" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdEmpresa" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CodigoCTP" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Provincia" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="Canton" Type="System.String" DbType="Char(2)" CanBeNull="true" />
      <Column Name="Distrito" Type="System.String" DbType="Char(2)" CanBeNull="true" />
      <Column Name="Estado" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ProvinciaDesc" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CantonDesc" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DistritoDesc" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.ConsultarEmpresa" Method="ConsultarEmpresa">
    <ElementType Name="ConsultarEmpresaResult">
      <Column Name="IdEmpresa" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IdTipoIdentificacion" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Identificacion" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Telefono" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Contacto" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Estado" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.ConsultarLinea" Method="ConsultarLinea">
    <Parameter Name="IdEmpresa" Parameter="idEmpresa" Type="System.Int32" DbType="Int" />
    <ElementType Name="ConsultarLineaResult">
      <Column Name="IdLinea" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdEmpresa" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CodigoCTP" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Provincia" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="Canton" Type="System.String" DbType="Char(2)" CanBeNull="true" />
      <Column Name="Distrito" Type="System.String" DbType="Char(2)" CanBeNull="true" />
      <Column Name="Estado" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ProvinciaDesc" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CantonDesc" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DistritoDesc" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.ConsultarUsuario" Method="ConsultarUsuario">
    <ElementType Name="ConsultarUsuarioResult">
      <Column Name="IdUsuario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Nombre2" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Apellido1" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Apellido2" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IdTipoIdentificacion" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Identificacion" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Saldo" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Telefono" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Correo" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Clave" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Estado" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.ConsultaUsuario" Method="ConsultaUsuario">
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Int32" DbType="Int" />
    <ElementType Name="ConsultaUsuarioResult">
      <Column Name="IdUsuario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Nombre2" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Apellido1" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Apellido2" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IdTipoIdentificacion" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Identificacion" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Saldo" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Telefono" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Correo" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Clave" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Estado" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.CreaLinea" Method="CreaLinea">
    <Parameter Name="IdEmpresa" Parameter="idEmpresa" Type="System.Int32" DbType="Int" />
    <Parameter Name="Descripcion" Parameter="descripcion" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="CodigoCTP" Parameter="codigoCTP" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Provincia" Parameter="provincia" Type="System.Char" DbType="Char(1)" />
    <Parameter Name="Canton" Parameter="canton" Type="System.String" DbType="Char(2)" />
    <Parameter Name="Distrito" Parameter="distrito" Type="System.String" DbType="Char(2)" />
    <Parameter Name="Estado" Parameter="estado" Type="System.Boolean" DbType="Bit" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CreaUsuario" Method="CreaUsuario">
    <Parameter Name="Nombre" Parameter="nombre" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Nombre2" Parameter="nombre2" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Apellido1" Parameter="apellido1" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Apellido2" Parameter="apellido2" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="IdTipoIdentificacion" Parameter="idTipoIdentificacion" Type="System.Int32" DbType="Int" />
    <Parameter Name="Identificacion" Parameter="identificacion" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Saldo" Parameter="saldo" Type="System.Decimal" DbType="Money" />
    <Parameter Name="Telefono" Parameter="telefono" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Correo" Parameter="correo" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Clave" Parameter="clave" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Estado" Parameter="estado" Type="System.Boolean" DbType="Bit" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Distritos" Method="Distritos">
    <Parameter Name="Provincia" Parameter="provincia" Type="System.Char" DbType="Char(1)" />
    <Parameter Name="Canton" Parameter="canton" Type="System.String" DbType="Char(2)" />
    <ElementType Name="DistritosResult">
      <Column Name="Provincia" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="Canton" Type="System.String" DbType="Char(2) NOT NULL" CanBeNull="false" />
      <Column Name="Distrito" Type="System.String" DbType="Char(2) NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.EliminaLinea" Method="EliminaLinea">
    <Parameter Name="IdEmpresa" Parameter="idEmpresa" Type="System.Int32" DbType="Int" />
    <Parameter Name="IdLinea" Parameter="idLinea" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.EliminaUsuario" Method="EliminaUsuario">
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Provincias" Method="Provincias">
    <ElementType Name="ProvinciasResult">
      <Column Name="Provincia" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.ValidaUsuario" Method="ValidaUsuario">
    <Parameter Name="Correo" Parameter="correo" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Clave" Parameter="clave" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="ValidaUsuarioResult">
      <Column Name="IdUsuario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Nombre2" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Apellido1" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Apellido2" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IdTipoIdentificacion" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Identificacion" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Saldo" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Telefono" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Correo" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Clave" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Estado" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>